CREATE TABLE countries (
    "Iso3166_1" CHAR(2) PRIMARY KEY,
    "Name" TEXT NOT NULL
);

INSERT INTO countries ("Iso3166_1", "Name") VALUES ('FI', 'Finland');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('AE', 'United Arab Emirates');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('NO', 'Norway');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('ZA', 'South Africa');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('YU', 'Yugoslavia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BG', 'Bulgaria');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('GP', 'Guadeloupe');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('US', 'United States');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('RU', 'Russian Federation');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('LB', 'Lebanon');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('JO', 'Jordan');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MT', 'Malta');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PS', 'Palestine, State of');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PA', 'Panama');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BW', 'Botswana');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('NL', 'Netherlands');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PL', 'Poland');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IT', 'Italy');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('TR', 'Turkey');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('SG', 'Singapore');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BD', 'Bangladesh');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CN', 'China');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BS', 'Bahamas');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PE', 'Peru');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('VE', 'Venezuela, Bolivarian Republic of');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('ES', 'Spain');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('NZ', 'New Zealand');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('SE', 'Sweden');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CH', 'Switzerland');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PR', 'Puerto Rico');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('JP', 'Japan');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('VN', 'Viet Nam');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CL', 'Chile');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PY', 'Paraguay');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('EC', 'Ecuador');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('HU', 'Hungary');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PH', 'Philippines');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('HK', 'Hong Kong');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('EE', 'Estonia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('LV', 'Latvia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('AR', 'Argentina');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BE', 'Belgium');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BR', 'Brazil');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('KR', 'Korea, Republic of');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CO', 'Colombia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CA', 'Canada');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('TH', 'Thailand');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('ID', 'Indonesia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CY', 'Cyprus');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('GR', 'Greece');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('DK', 'Denmark');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IS', 'Iceland');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('AT', 'Austria');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('CZ', 'Czechia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MN', 'Mongolia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('LU', 'Luxembourg');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('FR', 'France');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MY', 'Malaysia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('AU', 'Australia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('KZ', 'Kazakhstan');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('SA', 'Saudi Arabia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IE', 'Ireland');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MA', 'Morocco');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IL', 'Israel');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MC', 'Monaco');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('UA', 'Ukraine');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('DE', 'Germany');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('GB', 'United Kingdom');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('NG', 'Nigeria');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('RS', 'Serbia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('HR', 'Croatia');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('SU', 'USSR');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('QA', 'Qatar');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('AO', 'Angola');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('LI', 'Liechtenstein');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('PK', 'Pakistan');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('HN', 'Honduras');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IR', 'Iran, Islamic Republic of');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('MX', 'Mexico');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('IN', 'India');
INSERT INTO countries ("Iso3166_1", "Name") VALUES ('RO', 'Romania');
