CREATE TABLE spoken_languages (
    "Iso639_1" CHAR(2) PRIMARY KEY,
    "EnglishName" TEXT NOT NULL,
    "Name" TEXT
);

INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Kazakh', 'kk', 'қазақ');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Kannada', 'kn');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Thai', 'th', 'ภาษาไทย');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Bengali', 'bn', 'বাংলা');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Swahili', 'sw', 'Kiswahili');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Ido', 'io');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Ndebele', 'nd');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Khmer', 'km');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Divehi', 'dv');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Zulu', 'zu', 'isiZulu');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Cornish', 'kw');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Nepali', 'ne');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Inuktitut', 'iu');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Vietnamese', 'vi', 'Tiếng Việt');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Punjabi', 'pa', 'ਪੰਜਾਬੀ');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Slovak', 'sk', 'Slovenčina');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Norwegian', 'no', 'Norsk');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Gaelic', 'gd');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Breton', 'br');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Dzongkha', 'dz');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Galician', 'gl', 'Galego');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Swedish', 'sv', 'svenska');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('English', 'en', 'English');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Hindi', 'hi', 'हिन्दी');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Danish', 'da', 'Dansk');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Kurdish', 'ku');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Bosnian', 'bs', 'Bosanski');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Venda', 've');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Persian', 'fa', 'فارسی');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Hungarian', 'hu', 'Magyar');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Burmese', 'my');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Tagalog', 'tl');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Turkish', 'tr', 'Türkçe');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Dutch', 'nl', 'Nederlands');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Pushto', 'ps', 'پښتو');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('No Language', 'xx', 'No Language');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Mongolian', 'mn');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Cantonese', 'cn', '广州话 / 廣州話');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Tibetan', 'bo');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Catalan', 'ca', 'Català');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Telugu', 'te', 'తెలుగు');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Javanese', 'jv');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Tamil', 'ta', 'தமிழ்');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Urdu', 'ur', 'اردو');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('German', 'de', 'Deutsch');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Marathi', 'mr');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Bulgarian', 'bg', 'български език');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Icelandic', 'is', 'Íslenska');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Italian', 'it', 'Italiano');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Amharic', 'am');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Greek', 'el', 'ελληνικά');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Gujarati', 'gu');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Sanskrit', 'sa');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Korean', 'ko', '한국어/조선말');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Japanese', 'ja', '日本語');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Portuguese', 'pt', 'Português');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Xhosa', 'xh');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Lithuanian', 'lt', 'Lietuvių');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Finnish', 'fi', 'suomi');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Russian', 'ru', 'Pусский');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Navajo', 'nv');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Northern Sami', 'se');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Czech', 'cs', 'Český');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Hebrew', 'he', 'עִבְרִית');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Serbian', 'sr', 'Srpski');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Oriya', 'or');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Estonian', 'et', 'Eesti');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Somali', 'so', 'Somali');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Indonesian', 'id', 'Bahasa indonesia');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Armenian', 'hy');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Mandarin', 'zh', '普通话');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Arabic', 'ar', 'العربية');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Yiddish', 'yi');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Croatian', 'hr', 'Hrvatski');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Georgian', 'ka', 'ქართული');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Malayalam', 'ml');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Albanian', 'sq', 'shqip');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Akan', 'ak');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Haitian; Haitian Creole', 'ht');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Esperanto', 'eo', 'Esperanto');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Kongo', 'kg');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Guarani', 'gn');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Latin', 'la', 'Latin');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Moldavian', 'mo');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1") VALUES ('Abkhazian', 'ab');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Belarusian', 'be', 'беларуская мова');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Malay', 'ms', 'Bahasa melayu');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Afrikaans', 'af', 'Afrikaans');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Romanian', 'ro', 'Română');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Irish', 'ga', 'Gaeilge');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Ukrainian', 'uk', 'Український');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Polish', 'pl', 'Polski');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Spanish', 'es', 'Español');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('French', 'fr', 'Français');
INSERT INTO spoken_languages ("EnglishName", "Iso639_1", "Name") VALUES ('Basque', 'eu', 'euskera');
